export enum Color {
  WHITE = 'WHITE',

  BROWN = 'BROWN',

  GREEN = 'GREEN',

  YELLOW = 'YELLOW',

  GREY = 'GREY',

  PINK = 'PINK',

  BLUE = 'BLUE',

  RED = 'RED',

  BLACK = 'BLACK',

  PURPLE = 'PURPLE',

  PINK_GREY = 'PINK_GREY',

  RED_BLUE = 'RED_BLUE',

  WHITE_GREEN = 'WHITE_GREEN',

  BROWN_GREEN = 'BROWN_GREEN',

  WHITE_YELLOW = 'WHITE_YELLOW',

  YELLOW_BROWN = 'YELLOW_BROWN',

  WHITE_GREY = 'WHITE_GREY',

  GREY_BROWN = 'GREY_BROWN',

  WHITE_PINK = 'WHITE_PINK',

  PINK_BROWN = 'PINK_BROWN',

  WHITE_BLUE = 'WHITE_BLUE',

  BROWN_BLUE = 'BROWN_BLUE',

  WHITE_RED = 'WHITE_RED',

  BROWN_RED = 'BROWN_RED',

  WHITE_BLACK = 'WHITE_BLACK',

  BROWN_BLACK = 'BROWN_BLACK',

  GREY_GREEN = 'GREY_GREEN',

  YELLOW_GREY = 'YELLOW_GREY',

  PINK_GREEN = 'PINK_GREEN',

  YELLOW_PINK = 'YELLOW_PINK',

  GREEN_BLUE = 'GREEN_BLUE',

  YELLOW_BLUE = 'YELLOW_BLUE',

  GREEN_RED = 'GREEN_RED',

  YELLOW_RED = 'YELLOW_RED',

  GREEN_BLACK = 'GREEN_BLACK',

  YELLOW_BLACK = 'YELLOW_BLACK',

  GREY_BLUE = 'GREY_BLUE',

  PINK_BLUE = 'PINK_BLUE',

  GREY_RED = 'GREY_RED',

  PINK_RED = 'PINK_RED',

  GREY_BLACK = 'GREY_BLACK',

  PINK_BLACK = 'PINK_BLACK',

  BLUE_BLACK = 'BLUE_BLACK',

  RED_BLACK = 'RED_BLACK',

  WHITE_BROWN_BLACK = 'WHITE_BROWN_BLACK',

  YELLOW_GREEN_BLACK = 'YELLOW_GREEN_BLACK',

  GREY_PINK_BLACK = 'GREY_PINK_BLACK',

  RED_BLUE_BLACK = 'RED_BLUE_BLACK',

  WHITE_GREEN_BLACK = 'WHITE_GREEN_BLACK',

  BROWN_GREEN_BLACK = 'BROWN_GREEN_BLACK',

  WHITE_YELLOW_BLACK = 'WHITE_YELLOW_BLACK',

  YELLOW_BROWN_BLACK = 'YELLOW_BROWN_BLACK',

  WHITE_GREY_BLACK = 'WHITE_GREY_BLACK',

  GREY_BROWN_BLACK = 'GREY_BROWN_BLACK',

  WHITE_PINK_BLACK = 'WHITE_PINK_BLACK',

  PINK_BROWN_BLACK = 'PINK_BROWN_BLACK',

  WHITE_BLUE_BLACK = 'WHITE_BLUE_BLACK',

  BROWN_BLUE_BLACK = 'BROWN_BLUE_BLACK',

  WHITE_RED_BLACK = 'WHITE_RED_BLACK',

  BROWN_RED_BLACK = 'BROWN_RED_BLACK',

  BLACK_WHITE = 'BLACK_WHITE',
}
