export enum MarkingType {
  LIFTING = 'LIFTING',

  SPIRALLY_COLORED = 'SPIRALLY_COLORED',

  LONGITUDINALLY_COLORED = 'LONGITUDINALLY_COLORED',

  RINGY_COLORED = 'RINGY_COLORED',

  NUMBERED = 'NUMBERED',
}
