//  [OPERATION]
export enum OperationKind {
  CENTRAL_ASSEMBLY = 'CENTRAL_ASSEMBLY',

  CORE_ASSEMBLY = 'CORE_ASSEMBLY',

  INTERSTICE_ASSEMBLY = 'INTERSTICE_ASSEMBLY',

  TAPE_LAYING = 'TAPE_LAYING',

  SCREEN = 'SCREEN',

  STRIP_LAYING = 'STRIP_LAYING',

  PLAIT = 'PLAIT',

  CARRIER_PLAIT = 'CARRIER_PLAIT',

  SHEATHING = 'SHEATHING',

  FLAT_SHEATHING = 'FLAT_SHEATHING',

  CONTINUITY_WIRE_LONGIT_LAYING = 'CONTINUITY_WIRE_LONGIT_LAYING',
}
