//  [OPERATION]
export enum OperationKind {
  CENTRAL_ASSEMBLY = 'CENTRAL_ASSEMBLY',

  CORE_ASSEMBLY = 'CORE_ASSEMBLY',

  INTERSTICE_ASSEMBLY = 'INTERSTICE_ASSEMBLY',

  TAPE_LAYING = 'TAPE_LAYING',

  SCREEN = 'SCREEN',

  SHEATHING = 'SHEATHING',
}
